### ISSUE TITLE
Add way to get MD5 digest

### ISSUE THREAD

**Issue by humphd** [MPierre9/FileInfo#1]
We need a way to get the [MD5 digest](https://en.wikipedia.org/wiki/MD5) for a file at a given path.  For example, given a path like `"/home/kim/mydata.txt"`, which contains the text `The quick brown fox jumps over the lazy dog`, it should return `"9e107d9d372bb6826bd81d3542a419d6"`.

**Comment by MPierre9** [comment]
Working on it :)
