### ISSUE TITLE
Get a files size in bytes

### ISSUE THREAD

**Issue by MPierre9** [MPierre9/FileInfo#3]
We need a way to get a files size in bytes for a given path, for example `c:/project/code/index.js` would return `1254` bytes

**Comment by seanprashad** [comment]
Hi @MPierre9! I'd love to help with this bug but I've never written any Python before - do you recommend any specific docs/guides to help setup my local environment?

**Comment by MPierre9** [comment]
Hi @SeanPrashad you're more than welcome to take a jab at it. I'm new to Python too so we'll be in the same boat. I did the first couple lessons for Python [(Link)](https://www.codecademy.com/learn/learn-python) on Code Academy to learn the syntax since I already know languages like Java and C#. For the environment I'm using Visual Studio 2015 which has a Python Compiler built in and it works great (provided you download the Python template)

**Comment by seanprashad** [comment]
@MPierre9 I'll get right on it, thanks!
