### ISSUE TITLE
Function to return SHA1 Digest for a given path

### ISSUE THREAD

**Issue by MPierre9** [MPierre9/FileInfo#4]
We need a function that returns the SHA1 Digest for a given path for example say we have `c:/project/code/index.txt` which contains sensitive password information like `P@ssw0rd123` we need to retrieve the SHA1 which could be `fd4e1c67a2d28fced849ee1bb76e7391b93eb12`

**Comment by Mithilan16** [comment]
Hi @MPierre9 !, Do you mind if I try to resolve this bug?

**Comment by MPierre9** [comment]
@Mithilan16 Go for it! Let me know if you need any help 👍
